### ISSUE TITLE
Dataset missing many TCGA WGS samples for the 25 cancers that are present

### ISSUE THREAD

**Issue by hermidalc** [yge15/TCGA_Microbial_Content#5]
Do you know why the main dataset is missing many TCGA WGS samples for the 25 cancers that are present? At the GDC

If you go to the GDC and to the Cohort Builder web tool and build a query with

```
PROGRAM <- TCGA
EXPERIMENTAL STRATEGY <- WGS
DATA TYPE <- Aligned Reads
```

This results in 8,840 cases out of 11,428 total TCGA cases. Switch to "Table View" and download the case TSV for these 8,840 cases.

Count the unique cases per project. There are 33 cancers with WGS data:

```
> cases_df <- read.delim("cases.tsv")
> data.frame(table(cases_df$project.project_id))
        Var1 Freq
1   TCGA-ACC   74
2  TCGA-BLCA  411
3  TCGA-BRCA  952
4  TCGA-CESC  271
5  TCGA-CHOL   49
6  TCGA-COAD  371
7  TCGA-DLBC   42
8  TCGA-ESCA  118
9   TCGA-GBM  347
10 TCGA-HNSC  482
11 TCGA-KICH   86
12 TCGA-KIRC  124
13 TCGA-KIRP  216
14 TCGA-LAML   50
15  TCGA-LGG  461
16 TCGA-LIHC  324
17 TCGA-LUAD  464
18 TCGA-LUSC  337
19 TCGA-MESO   73
20   TCGA-OV  363
21 TCGA-PAAD  173
22 TCGA-PCPG  165
23 TCGA-PRAD  414
24 TCGA-READ  143
25 TCGA-SARC  223
26 TCGA-SKCM  223
27 TCGA-STAD  436
28 TCGA-TGCT  253
29 TCGA-THCA  477
30 TCGA-THYM  111
31 TCGA-UCEC  482
32  TCGA-UCS   50
33  TCGA-UVM   75
```

If you look at your metadata file for the 5,734 cases from 25 cancers in your dataset, you only included this many cases with WGS data in your dataset, which is much less than what is available at the GDC:

```
library(httr)
library(readxl)

download.file(
    "https://github.com/yge15/TCGA_Microbial_Content/raw/main/TableS12_Metadata-TCGA-WGS-5734-Samples.xlsx",
    "TableS12_Metadata-TCGA-WGS-5734-Samples.xlsx"
)
kraken_meta <- as.data.frame(
    read_excel("TableS12_Metadata-TCGA-WGS-5734-Samples.xlsx", progress = FALSE),
    stringsAsFactors = FALSE
)

> dim(kraken_meta)

[1] 5734   14

> data.frame(table(unique(kraken_meta[c("project_id", "case_id")])$project_id))

        Var1 Freq
1  TCGA-BLCA  116
2  TCGA-BRCA  118
3  TCGA-CESC   69
4  TCGA-COAD  110
5  TCGA-DLBC    7
6  TCGA-ESCA   53
7   TCGA-GBM   53
8  TCGA-HNSC  157
9  TCGA-KICH   50
10 TCGA-KIRC   42
11 TCGA-KIRP   38
12 TCGA-LAML   49
13  TCGA-LGG   86
14 TCGA-LIHC   54
15 TCGA-LUAD  234
16 TCGA-LUSC   50
17   TCGA-OV   58
18 TCGA-PRAD  122
19 TCGA-READ   44
20 TCGA-SARC   40
21 TCGA-SKCM  138
22 TCGA-STAD  128
23 TCGA-THCA  477
24 TCGA-UCEC  143
25  TCGA-UVM   51
```

**Comment by yge15** [comment]
Yes, we downloaded all available WGS samples as of late 2023. Apparently TCGA added more than 10K samples at the end of 2023, which we did not include in this analysis.

**Comment by hermidalc** [comment]
> Yes, we downloaded all available WGS samples as of late 2023. Apparently TCGA added more than 10K samples at the end of 2023, which we did not include in this analysis.

I apologize for challenging this but I know this isn't the case. Our lab has worked with TCGA data for many years and since at least 2018-2019 they've had this many WGS samples as I've shown above. TCGA is a completed program since 2019 and they didn't add any new samples.

**Comment by hermidalc** [comment]
> Yes, we downloaded all available WGS samples as of late 2023. Apparently TCGA added more than 10K samples at the end of 2023, which we did not include in this analysis.

Ok thank you for explaining this and for your time. It's strange that TCGA added so many new WGS samples I thought TCGA was completed for some time now.

**Comment by hermidalc** [comment]
Thank you again @yge15 for your help answering questions I very much appreciate it. Posting for others wondering the same thing that indeed like you said TCGA added many WGS samples Dec 2023 and Mar 2024

http://gdc.cancer.gov/news-and-announcements/new-tcga-whole-genome-data-and-five-new-nci-match-projects

http://gdc.cancer.gov/content/additional-tcga-wgs-alignments-and-variant-calls-new-nci-match-trial-arms-data-and-more
